[package]
name = "oxibrowser-webapi"
version = "0.14.1"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true
description = "DOM and WebAPI implementations backed by html5ever"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
html5ever = { workspace = true }
markup5ever = { workspace = true }
string_cache = { workspace = true }
thiserror = { workspace = true }
